# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise32"

  # Provision
  config.vm.provision "shell", inline: "cd /home/vagrant", privileged: true
  config.vm.provision "shell", inline: "wget https://bootstrap.pypa.io/get-pip.py", privileged: true
  config.vm.provision "shell", inline: "python get-pip.py", privileged: true
  config.vm.provision "shell", inline: "apt-get update", privileged: true
  config.vm.provision "shell", inline: "apt-get -y install python-dev", privileged: true
  config.vm.provision "shell", inline: "apt-get -y install git", privileged: true
  config.vm.provision "shell", inline: "apt-get -y install libxml2-dev libxslt1-dev", privileged: true
  config.vm.provision "shell", inline: "pip install -r /vagrant/requirements.txt", privileged: true
end
