__author__ = 'arobres, jfernandez'

# PUPPET WRAPPER CONFIGURATION
PUPPET_MASTER_PROTOCOL = 'https'
PUPPET_WRAPPER_IP = 'puppet-master.dev-havana.fi-ware.org'
PUPPET_WRAPPER_PORT = 8443
PUPPET_MASTER_USERNAME = 'root'
PUPPET_MASTER_PWD = '**********'
PUPPET_WRAPPER_MONGODB_PORT = 27017
PUPPET_WRAPPER_MONGODB_DB_NAME = 'puppetWrapper'
PUPPET_WRAPPER_MONGODB_COLLECTION = 'nodes'

#AUTHENTICATION
CONFIG_KEYSTONE_URL = 'http://130.206.80.57:4731/v2.0/tokens'
CONFIG_KEYSTONE_TENANT_NAME_VALUE = '**********'
CONFIG_KEYSTONE_USERNAME_VALUE = '**********'
CONFIG_KEYSTONE_PWD_VALUE = '**********'
