__author__ = 'arobres'


#PUPPET PARAMETERS

PUPPET_MASTER_PATH = u'/etc/puppet/'
PUPPET_MASTER_MODULES = PUPPET_MASTER_PATH + u'modules/'
PUPPET_MASTER_MANIFESTS = PUPPET_MASTER_PATH + u'manifests/'
PUPPET_MASTER_SITE = PUPPET_MASTER_MANIFESTS + u'site.pp'
PUPPET_MASTER_SPECIFIC_MANIFEST = PUPPET_MASTER_MANIFESTS + u'{}/{}.pp'
PUPPET_MASTER_SPECIFIC_MODULE = PUPPET_MASTER_MODULES + u'{}/manifests'
SITE_PP_TEXT = u"import '{}/*.pp'"

#INSTALL / UNINSTALL / GENERATE BODYS

INSTALL_NODE_NAME = u'id'
INSTALL_GROUP_NAME = u'groupName'
INSTALL_MANIFEST_GENERATED = u'manifestGenerated'

#ACTIONS

INSTALL = u'install'
UNINSTALL = u'uninstall'

#GENERATE CONSTANTS

ACTION = u'action'
SOFTWARE_NAME = u'software_name'
VERSION = u'version'

#DOWNLOAD CONSTANTS

URL = u'URL'
MODULE_NAME = u'module_name'
REPOSITORY = u'repository'

#FABRIC CONSTANT

FABRIC_RESULT_EXECUTE = u'<local-only>'

